apiVersion: apps/v1
kind: Deployment
metadata:
  name: playwright-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playwright-service
  template:
    metadata:
      labels:
        app: playwright-service
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
      - name: playwright-service
        image: ghcr.io/winkk-dev/firecrawl-playwright:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: firecrawl-config
---
apiVersion: v1
kind: Service
metadata:
  name: playwright-service
spec:
  selector:
    app: playwright-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
