/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Extracts base href from HTML */
export declare function extractBaseHref(html: string, url: string): string

/** Extracts links from HTML */
export declare function extractLinks(html: string): Array<string>

/** Extracts metadata from HTML */
export declare function extractMetadata(html: string): Record<string, any>

/** For JSON pages retrieved by browser engines, this function can be used to transform it back into valid JSON. */
export declare function getInnerJson(html: string): string

/** Converts HTML to Markdown */
export declare function htmlToMarkdown(html: string): string

export interface TranformHtmlOptions {
  html: string
  url: string
  includeTags: Array<string>
  excludeTags: Array<string>
  onlyMainContent: boolean
  omceSignatures?: Array<string>
}

/** Transforms rawHtml to html (formerly removeUnwantedElements) */
export declare function transformHtml(opts: TranformHtmlOptions): string
