export const extractConfig = {
  RERANKING: {
    MAX_INITIAL_RANKING_LIMIT: 1000,
    MAX_RANKING_LIMIT_FOR_RELEVANCE: 100,
    INITIAL_SCORE_THRESHOLD_FOR_RELEVANCE: 0.75,
    FALLBACK_SCORE_THRESHOLD_FOR_RELEVANCE: 0.5,
    MIN_REQUIRED_LINKS: 1,
  },
  DEDUPLICATION: {
    MAX_TOKENS: 4096,
  },
};
export const CUSTOM_U_TEAMS = ["874d40cc-a5c0-4e93-b661-9ddfbad5e51e"];
