# Pick your baseUrl here:
@baseUrl = http://localhost:3002
# @baseUrl = https://api.firecrawl.dev

### Scrape Website
# @name scrape
POST {{baseUrl}}/v1/scrape HTTP/1.1
Authorization: Bearer {{$dotenv TEST_API_KEY}}
content-type: application/json

{
  "url":"https://firecrawl.dev"
}

### Crawl Website
# @name crawl
POST {{baseUrl}}/v1/crawl HTTP/1.1
Authorization: Bearer {{$dotenv TEST_API_KEY}}
content-type: application/json

{
  "url": "https://firecrawl.dev"
}

### Check Crawl Status
@crawlId = {{crawl.response.body.$.id}}
# @name crawlStatus
GET {{baseUrl}}/v1/crawl/{{crawlId}} HTTP/1.1
Authorization: Bearer {{$dotenv TEST_API_KEY}}

### Cancel Crawl
@crawlId = {{crawl.response.body.$.id}}
# @name cancelCrawl
DELETE {{baseUrl}}/v1/crawl/{{crawlId}} HTTP/1.1
Authorization: Bearer {{$dotenv TEST_API_KEY}}

### Batch Scrape Websites
# @name batchScrape
POST {{baseUrl}}/v1/batch/scrape HTTP/1.1
Authorization: Bearer {{$dotenv TEST_API_KEY}}
content-type: application/json

{
  "urls": [
    "firecrawl.dev",
    "mendable.ai"
  ]
}

### Check Batch Scrape Status
@batchScrapeId = {{batchScrape.response.body.$.id}}
# @name batchScrapeStatus
GET {{baseUrl}}/v1/crawl/{{batchScrapeId}} HTTP/1.1
Authorization: Bearer {{$dotenv TEST_API_KEY}}


### Map Website
# @name map
POST {{baseUrl}}/v1/map HTTP/1.1
Authorization: Bearer {{$dotenv TEST_API_KEY}}
content-type: application/json

{
  "url": "firecrawl.dev",
  "sitemapOnly": true
}

### Extract Firecrawl Title
# @name extractFirecrawl
POST {{baseUrl}}/v1/extract HTTP/1.1
Authorization: Bearer {{$dotenv TEST_API_KEY}}
content-type: application/json

{
  "urls": [
    "https://firecrawl.dev/blog"
  ],
  "origin": "api-sdk",
  "prompt": "Extract all the blog titles from the page, is multity entity = true",
  "schema": {
    "type": "object",
    "properties": {
      "blog_titles": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "required": ["blog_titles"]
  }
}

###
@extractFirecrawlId = {{extractFirecrawl.response.body.$.id}}
# @name extractFirecrawlStatus 
GET {{baseUrl}}/v1/extract/{{extractFirecrawlId}} HTTP/1.1
Authorization: Bearer {{$dotenv TEST_API_KEY}}

###
DELETE {{baseUrl}}/v1/crawl/c94136f9-86c1-4a97-966c-1c8e0274778f HTTP/1.1
Authorization: Bearer {{$dotenv TEST_API_KEY}}
